name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  pull_request:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint:check

      - name: Run Unit Tests
        run: pnpm test

      - name: Run Production Build
        run: pnpm build
